### ISSUE TITLE
KeyError issue running basic sample request 

### ISSUE THREAD

**Issue by PierreNei** [JCyberSec/URLscanAPI#1]
```
$ python3.8 Public-main.py search -t 'page.url:"tipobet365gir"' -e url -d 3d
Traceback (most recent call last):
  File "Public-main.py", line 123, in <module>
    main()
  File "Public-main.py", line 117, in main
    search(args.term, args.size, args.date, args.extract)
  File "Public-main.py", line 96, in search
    for i in range(len(result['results'])):
KeyError: 'results'

$ python3.8 --version
Python 3.8.6
```

**Comment by JCyberSec** [comment]
I am unable to replicate this issue with the new version. Please test with the new patch which has been uploaded. Also the search you have entered returns 0 results: https://urlscan.io/search/#page.url%3A%22tipobet365gir%22

Try a search which returns values.

**Comment by PierreNei** [comment]
urlscan.io shows 27 results for a search on "youtube", I still get the same error (I ran git pull just now) with the latest code when searching for "youtube":
```
$ python3.8 Public-main.py search -t 'page.url:"youtube"' -e url -d 3d
Traceback (most recent call last):
  File "Public-main.py", line 132, in <module>
    main()
  File "Public-main.py", line 124, in main
    search(args.term, args.size, args.date, args.extract)
  File "Public-main.py", line 103, in search
    for i in range(len(result['results'])):
KeyError: 'results'
```

**Comment by JCyberSec** [comment]
You have not added your API key to line 12.

You need to add your URLScan API key. 

Close issue as able to reproduce the error and able to resolve the error without any new code updates.

**Comment by PierreNei** [comment]
Got it, thanks!
